### ISSUE TITLE
App not compatible with Stretch / YunoHost 3.0

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/weblate_ynh#11]
Hellow !

Apparently fails to install on YunoHost 3.0 according to the CI : https://ci-stretch.nohost.me/jenkins/job/weblate%20(Community)/lastBuild/consoleFull

This error : 
```
**Warning: yunohost.hook <lambda> - [926.1] sed: can't read /etc/postgresql/9.4/main/pg_hba.conf: No such file or directory**
```

indicates that there's a hard-coded reference to postgresql 9.4 somewhere, but Stretch runs 9.6 :stuck_out_tongue_winking_eye:

**Comment by Jibec** [comment]
It is in testing, I'm stuck with another issue...
-- 
Jean-Baptiste Holcroft

**Comment by alexAubin** [comment]
Alrighty, closing then :sweat_smile: Thanks !
