### ISSUE TITLE
This app doesn't work as expected when having "/" as the URL

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost-Apps/weblate_ynh#2]
This breaks the static files. To fix it I had to change:

    STATIC_URL = '{0}/static/'.format(URL_PREFIX)

To

    STATIC_URL = '/static/'

And in the nginx file, all the `location //static` had to be replaced by `location /static`

**Comment by Psycojoker** [comment]
Actually the real fix for the settings.py is to replace `URL_PREFIX = '/'` to `URL_PREFIX = ''` I think.

**Comment by Psycojoker** [comment]
And I actually had to remove this line in nginx conf `uwsgi_param SCRIPT_NAME /;` it was breaking all urls besides '/'.

**Comment by Jibec** [comment]
This is fixed by https://github.com/YunoHost-Apps/weblate_ynh/commit/2ad658b9219de7f61f27f4b4fd00338113da123f
