### ISSUE TITLE
use logrotate for /var/log/uwsgi/app/weblate

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost-Apps/weblate_ynh#22]
Hello,

Would it be possible to add logrotate to handle weblate logs? On saperlipopette they end up taking 7.7 Gb of place :x 

Apparently you simply need to use the "ynh_use_logrotate" helper as shown here https://yunohost.org/#/packaging_apps_helpers_en

Kind regards,

**Comment by Jibec** [comment]
Oh, is dear, I noticed this email every once in a while and without understanding why etckeeper was eating all my disk. Is this the same issue you're having?

**Comment by Psycojoker** [comment]
I don't think so, etc keeper is only for things in /etc, logs are in /var/log so that shouldn't be linked.

You can try to run a "ncdu /etc" to debug that, you either has a super very mega often file changing in /etc or very huge files that shouldn't be there.

**Comment by Jibec** [comment]
Hello, this should be fix by https://github.com/YunoHost-Apps/weblate_ynh/pull/23

your review would be useful, but don't use it yet for production, I only did basic tests with VM+package check, not with my own server yet

**Comment by Jibec** [comment]
should be fixed by: https://github.com/YunoHost-Apps/weblate_ynh/pull/23 please reopen this issue if required

**Comment by Psycojoker** [comment]
Never implemented this myself, sorry :x (but LGTM)

Thx for your work :heart:
