### ISSUE TITLE
django good practice to save local settings

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/weblate_ynh#24]
could you append a thing like:

```python
try:
    import * from .local_settings
except ImportError:
    pass
```

at the end of the settings.py? it will allow user to override only the values they want to change in a local_settings.py files next to the settings.py file.

**Comment by kay0u** [comment]
Thanks for the idea, I implemented it in this [PR](https://github.com/YunoHost-Apps/weblate_ynh/pull/35)
