### ISSUE TITLE
Erreur interne du serveur lorsque création composant

### ISSUE THREAD

**Issue by MaximeMichaud** [YunoHost-Apps/weblate_ynh#25]
![image](https://user-images.githubusercontent.com/14856114/64491407-42112e80-d236-11e9-81ad-aaba49fe52dc.png)

Pourtant, c'était des composants vierge & j'ai testé sur deux VPS différent avec une installation vierge de yunohost.
Et je n'ai pas trouver le moyen d'avoir les logs concernant l'erreur.

**Comment by Jibec** [comment]
Dans /car/log/weblate il y a le log de celery, sinon il envoie un courriel avec le contenu de l'erreur

**Comment by MaximeMichaud** [comment]
Y'a vraiment rien dans /var/log/weblate
Je commence vraiment vraiment vraiment en avoir marre de Weblate.
Déjà j'ai dû mettre à jour leur documentation. Et là y'a que avec yunohost que j'ai eu des résultats satisfaisants. Ça fait 2 putains de jours que je m'efforce de faire fonctionner ce foutoir.
Y'a que Docker qui fonctionnait, mais même encore c'était pas plaisant.

**Comment by Jibec** [comment]
Weblate semble simple, mais à administrer ce n'est pas si facile, peut-être que ton projet est opensource et que je peux te faire un territorial ? Une fois qu'on comprends la mécanique, on est complètement autonome.

Je suis un peu surpris que tu n'aies pas de logs. Essaye `sudo find /var/log/ | grep weblate` puis cherche les différents fichiers.

**Comment by MaximeMichaud** [comment]
Non, malheureusement ce n'est pas vraiment un projet opensource.
Pour les logs, il n'y a que ceux de yunohost et nginx. (Rien qui concerne le problème)
J'ai reproduit l'erreur pour voir s'il y avait du nouveau et non, absolument rien du tout.
Pour celery, cela n'update même pas le fichier de log & weblate : {60 vars in 1269 bytes} [Sun Sep  8 19:57:56 2019] POST /create/component/ => generated 8111 bytes in 714 msecs (HTTP/2.0 500) 9 headers in 499 bytes (1 switches on core 0)

**Comment by Jibec** [comment]
Alors modifie le fichier de configuration et met DEBUG à True. Puis redémarre le démon Weblate avec 'systemcl restart weblate' et refait ton import de composant. Tu auras plus de détails.

Autre alternative, tu crées un projet fantôme sur github avec la même configuration de fichiers que ton projet, et on fait un test dessus. De toute façon, tout ce qui est utile ce sont les fichiers de traduction.

**Comment by MaximeMichaud** [comment]
Pardon, mais où puis-je trouver ce fichier de configuration ?

**Comment by Jibec** [comment]
As tu reçu un mail après l'installation de weblate ? Dedans tu dois avoir l'adresse

**Comment by MaximeMichaud** [comment]
RepositoryException at /create/component/
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
Je l'ai configuré, mais semblerait faut que ce soit dans le repo directement, mais je ne connais pas le chemin.

**Comment by MaximeMichaud** [comment]
Du coup, tu as une idée? Je n'ai toujours pas trouver comment config l'utilisateur pour weblate précisement.

**Comment by Jibec** [comment]
Le message que tu m'as donné n'aide malheureusement pas. Peux-tu répondre à ma dernière question ?

**Comment by MaximeMichaud** [comment]
Justement, cela provient du mail. 
Mail complet : https://pastebin.com/NBpB69ND
Du coup, comment on fixe ça? J'aimerais bien que mon weblate puisse fonctionner.

**Comment by MaximeMichaud** [comment]
J'ai contacté le maintener de Weblate.. ceci est un bug qui est fix dans la version 3.8.1
Merci d'update :)
https://github.com/WeblateOrg/docker/issues/364

**Comment by Jibec** [comment]
tu utilises docker ?

**Comment by MaximeMichaud** [comment]
Non.. mais la personne ayant eu le problème étant sur Docker.
Dans ton cas, suffirait uniquement de mettre à jour Weblate vers 3.8.1
Sinon, Weblate est complètement inutilisable ;)
