### ISSUE TITLE
Email errors / account creation impossible

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/weblate_ynh#38]
Hello,
I just installed a fresh WebLate on my YunoHost, without any problem.
I've read that the LDAP integration does not exists and that's fine for me.
So, I tried to create an account, but I never received the mail.

Then, I tried to contact tho administrator (via weblate), and there is a server error whenn I send the message.

3rd thing I tried : log in with my YunoHost login/pass : error
But when I tried to create an account with the user I set to bi the admin, I have a message that it already exists (but with which password ?).

Some time after, I received a few mails from weblate, but not the account creation or the message sent, they were mails about a server error.

There was no error log on the server (maybe somewhere else than /var/log/weblate/ ?) so there is the content of one of the mails : https://paste.yunohost.org/ejewuketam.http
(each mail came in pair, one fulltext, and one in HTML)
They seems to contain similar content so I copied the fulltext one.

**Comment by ashledombos** [comment]
Hi @supermamie 
I guess you've found it since then, but it may help other people, after a look at the install script, I've seen the default admin password is «weblate»

https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/install#L188

**Comment by supermamie** [comment]
Thanks for this info, so now I am logged with an account :)
I still can not create other account because it is still impossible to send mails, but at least I can try to learn how to use Weblate :smile:

**Comment by kay0u** [comment]
Hi!

Thank you for your report, this [commit](https://github.com/YunoHost-Apps/weblate_ynh/pull/39/commits/81ec8b36ce41a620817c131f6d5b5725e81b4528) should fix the issue.
Moreover, I added a password request during installation. No more default unsecured password
