### ISSUE TITLE
Update to 4.6.1

### ISSUE THREAD

**Issue by Xia0ben** [YunoHost-Apps/weblate_ynh#43]
Hello,

Thank you for this Weblate package for Yunohost, it really is one of the easiest ways available to get it running quickly. So far, it works like a charm !

Weblate notified me of the latest version available today when I opened it, and I thought it would be a good idea to open an issue here to keep track of the update of the Yunohost package ;-).

I was also wondering if there was a patreon/whatever set up to encourage the maintenance efforts of this app that I find particularly useful.

Wish you a very nice day !

**Comment by kay0u** [comment]
Hi!

Thank you for this issue, and sorry for the delay.

Even though we are now at version 4.7, feel free to do a PR for future releases if you know how to do it and have time to devote to this task. ([it's not complicated](https://github.com/YunoHost-Apps/weblate_ynh/commit/88b1816c06fa9e823c70eb02bc9b77531ae6fe9e)).

> I was also wondering if there was a patreon/whatever set up to encourage the maintenance efforts of this app that I find particularly useful.

I am the unofficial maintainer for now, but anyone who wants to take over this app is welcome. If you want to support YunoHost, you can do it via https://donate.yunohost.org/
