### ISSUE TITLE
is there a way to control service within yunohost?

### ISSUE THREAD

**Issue by mrPsycho** [YunoHost-Apps/weblate_ynh#5]
hello,

on https://yunohost/yunohost/admin/#/services/weblate.service
buttons doesn't work. 
also, log is empty.

**Comment by mrPsycho** [comment]
but, anyway, i would like just to know - how to restart service?

**Comment by mrPsycho** [comment]
okey. i find it. 

but, by default there is no pid file, so i cant use 'uwsgi --reload /path/to/pidfile'
so i created simple pull request.

**Comment by Jibec** [comment]
Hi, thank you for your bug report and your pull request.
The uwsgi service in master sucks. This was my first attempt with no knowledge...
Can you please have a look at the testing branch? I'm sure you'll like it.

**Comment by mrPsycho** [comment]
oh. looks cool.

**Comment by mrPsycho** [comment]
thanks!

**Comment by Jibec** [comment]
Glad you like it :) I would love to get your help, just tell me if installing weblate master and then update to testing works fine for you!
I tried it in my dev server and it works fine, but I'll be pleased to have someone to confirm it, we are not so many using weblate as administrator.

**Comment by mrPsycho** [comment]
i reinstalled it with:
```
yunohost app install https://github.com/YunoHost-Apps/weblate_ynh/tree/testing
```
it finished without errors,

but now i see 404 on `https://weblate.domain/accounts/login/`

**Comment by mrPsycho** [comment]
also, 
what if to add something like: 
```
try:
    from settings_auth import *
except ImportError:
    pass
```
to the settings.py  at the end as post-install step?

in that case anyone can create file settings_auth.py and fill it with needed variables. 
and it is much easier to support on upgrades.
