### ISSUE TITLE
Is there a reason github token is required?

### ISSUE THREAD

**Issue by milouse** [YunoHost-Apps/weblate_ynh#60]
This is a pure curiosity question: I plan to install this app on my yunohost instance, but I’m stuck at setup, due to the github token requirement. However, as all my git repository are stored elsewhere, I don’t plan to use github integration, thus this requirement sounds superfluous to me. As you can see, I do have a github account, thus I could create such token, but I’m just curious about the necessity of it.

**Comment by kay0u** [comment]
It's not super intuitive, but you can put garbage values like "xxx" in the username and the token fields, I should put these values as optional, but I don't have time to do it right now
