### ISSUE TITLE
URL Problem

### ISSUE THREAD

**Issue by BoFFire** [YunoHost-Apps/weblate_ynh#7]
Hi,
Problem with ARCH :

`+ wget --quiet https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-i386-2.3.0-pre10.tgz`

The correct URL is without "i" before 386 : https://github.com/github/hub/releases/download/v2.3.0-pre10/hub-linux-386-2.3.0-pre10.tgz

Best regards,

**Comment by Jibec** [comment]
I'm sorry I didn't notice this issue, this should be fixed in master, please confirm and reopen if needed
